adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

urlpatterns = [
    path('main/', adminapp.main, name='main'),
    path('persons/read/', adminapp.PersonsListView.as_view(), name='persons'),
    path('persons/create/', adminapp.PersonCreateView.as_view(), name='person_create'),
    re_path(r'^persons/update/(?P<pk>\d+)/$', adminapp.PersonUpdateView.as_view(), name='person_update'),
    re_path(r'^persons/delete/(?P<pk>\d+)/$', adminapp.PersonDeleteView.as_view(), name='person_delete'),
    path('key_words/read/', adminapp.KeywordsListView.as_view(), name='key_words'),
    path('key_words/create/', adminapp.KeywordCreateView.as_view(), name='key_word_create'),
    re_path(r'^key_words/update/(?P<pk>\d+)/$', adminapp.KeywordUpdateView.as_view(), name='key_word_update'),
    re_path(r'^key_words/delete/(?P<pk>\d+)/$', adminapp.KeywordDeleteView.as_view(), name='key_word_delete'),
    path('sites/read/', adminapp.SitesListView.as_view(), name='sites'),
    path('sites/create/', adminapp.SiteCreateView.as_view(), name='site_create'),
    re_path(r'^sites/update/(?P<pk>\d+)/$', adminapp.SiteUpdateView.as_view(), name='site_update'),
    re_path(r'^sites/delete/(?P<pk>\d+)/$', adminapp.SiteDeleteView.as_view(), name='site_delete'),
    path('pages/read/', adminapp.PagesListView.as_view(), name='pages'),
    path('pages/create/', adminapp.PageCreateView.as_view(), name='page_create'),
    re_path(r'^pages/update/(?P<pk>\d+)/$', adminapp.PageUpdateView.as_view(), name='page_update'),
    re_path(r'^pages/delete/(?P<pk>\d+)/$', adminapp.PageDeleteView.as_view(), name='page_delete'),
    path('person_page_ranks/read/', adminapp.PersonPageRanksListView.as_view(), name='person_page_ranks'),
    path('person_page_ranks/create/', adminapp.PersonPageRankCreateView.as_view(), name='person_page_rank_create'),
    re_path(r'^person_page_ranks/update/(?P<pk>\d+)/$', adminapp.PersonPageRankUpdateView.as_view(),
            name='person_page_rank_update'),
    re_path(r'^person_page_ranks/delete/(?P<pk>\d+)/$', adminapp.PersonPageRankDeleteView.as_view(),
            name='person_page_rank_delete'),
    # path('sites/link/', adminapp.sites_link, name='site_link'),
    path('sites/export/', adminapp.export, name='export'),
    path('sites/link/', adminapp.SitesLinkView.as_view(), name='site_link'),
    path('sites/link/renew/', adminapp.links_renew, name='link_renew'),
    # path('pages/detail/', adminapp.PageDetail.as_view(), name='page_detail'),
    # path('pages/detail/(<int:page>/)', adminapp.PageDetail.as_view(), name='page_detail'),
    re_path(r'^pages/detail/(?P<page>\d+)?$', adminapp.PageDetail.as_view(), name='page_detail'),
    # re_path(r'^sites/detail/view/(?P<page>\d+)$', adminapp.SiteDetailView.as_view(), name='site_detail_view'),
    # path('sites/detail/view/page<int:page>/', adminapp.PagSiteDetailView.as_view(), name='site_detail_view_pag'),
    # re_path('sites/detail/view/(?P<pk>\d+)/$', adminapp.detail_renew, name='site_detail_view'),
]

authapp/urls.py
import authapp.views as authapp
from django.urls import path, re_path
# from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm,\
#     password_reset_complete, password_change_done
# from django.conf.urls import url


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('change/', authapp.change_password, name='change'),
    path('password-reset/', authapp.password_reset, name='password_reset'),
    path('password-reset/done/', authapp.password_reset_done, name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', authapp.password_reset_confirm,
            name='password_reset_confirm'),
    path('password-reset/complete/', authapp.password_reset_complete, name='password_reset_complete'),
]

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

urlpatterns = [
    path('', mainapp.index, name='index'),
]

webadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('mainapp.urls', 'mainapp',), namespace='main')),
    path('myadmin/', include(('adminapp.urls', 'adminapp',), namespace='myadmin')),
    path('auth/', include(('authapp.urls', 'authapp',), namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render


def index(request):
    title = 'Главная'
    content = {'title': title}

    return render(request, 'mainapp/index.html', content)

mainapp/templates/mainapp/includes/inc_menu.html
<nav class="menu">
    <ul>
        {% if user.is_authenticated %}
        {% url 'auth:edit' as auth_link %}
        <li>
            {% if request.path == auth_link %}
            <a href="{% url 'auth:edit' %}" class="active">{{user.first_name|default:"Пользователь"|title}}</a>
            {% else %}
            <a href="{% url 'auth:edit' %}">{{user.first_name|default:"Пользователь"|title}}</a>
            {% endif %}
        </li>
        {% endif %}
        {% if user.is_superuser %}
        {% url 'myadmin:main' as auth_link %}
        <li>
            {% if 'myadmin' in request.path %}
            <a href="{% url 'myadmin:main' %}" class="active">Админ</a>
            {% else %}
            <a href="{% url 'myadmin:main' %}">Админ</a>
            {% endif %}
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">Выйти</a>
            {% else %}
            {% url 'auth:login' as login_link %}
            {% if request.path == login_link %}
            <a href="{% url 'auth:login' %}" class="active">Войти</a>
            {% else %}
            <a href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
            {% endif %}
        </li>
    </ul>
</nav>
