authapp/urls.py
import authapp.views as authapp
from django.urls import path, re_path
# from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm,\
#     password_reset_complete, password_change_done
# from django.conf.urls import url


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('change/', authapp.change_password, name='change'),
    path('password-reset/', authapp.password_reset, name='password_reset'),
    path('password-reset/done/', authapp.password_reset_done, name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', authapp.password_reset_confirm,
            name='password_reset_confirm'),
    path('password-reset/complete/', authapp.password_reset_complete, name='password_reset_complete'),
]

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

urlpatterns = [
    path('', mainapp.index, name='index'),
]

webadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('mainapp.urls', 'mainapp',), namespace='main')),
    path('myadmin/', include(('adminapp.urls', 'adminapp',), namespace='myadmin')),
    path('auth/', include(('authapp.urls', 'authapp',), namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

authapp/models.py
from django.db import models

# Create your models here.

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self). __init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_control input'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        # fields = '__all__'
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'is_superuser')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_username(self):
        data = self.cleaned_data['username']
        if len(data) < 3:
            raise forms.ValidationError('username не должно быть короче 3 символов!')

        return data


class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'password', 'email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_username(self):
        data = self.cleaned_data['username']
        if len(data) < 3:
            raise forms.ValidationError('username не должно быть короче 3 символов!')

        return data

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import UserLoginForm
from django.contrib import auth
from django.urls import reverse
from authapp.forms import UserRegisterForm
from authapp.forms import UserEditForm
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import update_session_auth_hash, get_user_model

import warnings
from django.conf import settings
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import resolve_url
from django.template.response import TemplateResponse
from django.utils.deprecation import RemovedInDjango21Warning
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

UserModel = get_user_model()


def login(request):
    title = 'Вход'
    login_form = UserLoginForm(data=request.POST or None)

    _next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main:index'))

    content = {
        'title': title,
        'login_form': login_form,
        'next': _next
    }

    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    title = 'Регистрация'

    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = UserRegisterForm()

    content = {'title': title, 'register_form': register_form}
    return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'Редактирование'

    if request.method == 'POST':
        edit_form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
            edit_form = UserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}
    return render(request, 'authapp/edit.html', content)


def change_password(request):
    title = 'Изменение пароля'

    if request.method == 'POST':
        change_pass_form = PasswordChangeForm(data=request.POST, user=request.user)

        if change_pass_form.is_valid():
            change_pass_form.save()
            update_session_auth_hash(request, change_pass_form.user)
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        change_pass_form = PasswordChangeForm(user=request.user)

    content = {'title': title, 'change_pass_form': change_pass_form}
    return render(request, 'authapp/change_password.html', content)


@csrf_protect
def password_reset(request,
                   template_name='authapp/password_reset_form.html',
                   email_template_name='authapp/password_reset_email.html',
                   subject_template_name='authapp/password_reset_subject.txt',
                   password_reset_form=PasswordResetForm,
                   token_generator=default_token_generator,
                   post_reset_redirect=None,
                   from_email=None,
                   extra_context=None,
                   html_email_template_name=None,
                   extra_email_context=None):
    warnings.warn("The password_reset() view is superseded by the "
                  "class-based PasswordResetView().",
                  RemovedInDjango21Warning, stacklevel=2)
    if post_reset_redirect is None:
        post_reset_redirect = reverse('auth:password_reset_done')
    else:
        post_reset_redirect = resolve_url(post_reset_redirect)
    if request.method == "POST":
        form = password_reset_form(request.POST)
        if form.is_valid():
            opts = {
                'use_https': request.is_secure(),
                'token_generator': token_generator,
                'from_email': from_email,
                'email_template_name': email_template_name,
                'subject_template_name': subject_template_name,
                'request': request,
                'html_email_template_name': html_email_template_name,
                'extra_email_context': extra_email_context,
            }
            form.save(**opts)
            return HttpResponseRedirect(post_reset_redirect)
    else:
        form = password_reset_form()
    context = {
        'form': form,
        'title': _('Password reset'),
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)


def password_reset_done(request,
                        template_name='authapp/password_reset_done.html',
                        extra_context=None):
    warnings.warn("The password_reset_done() view is superseded by the "
                  "class-based PasswordResetDoneView().",
                  RemovedInDjango21Warning, stacklevel=2)
    context = {
        'title': _('Password reset sent'),
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)


# Doesn't need csrf_protect since no-one can guess the URL
@sensitive_post_parameters()
@never_cache
def password_reset_confirm(request, uidb64=None, token=None,
                           template_name='authapp/password_reset_confirm.html',
                           token_generator=default_token_generator,
                           set_password_form=SetPasswordForm,
                           post_reset_redirect=None,
                           extra_context=None):
    """
    Check the hash in a password reset link and present a form for entering a
    new password.
    """
    warnings.warn("The password_reset_confirm() view is superseded by the "
                  "class-based PasswordResetConfirmView().",
                  RemovedInDjango21Warning, stacklevel=2)
    assert uidb64 is not None and token is not None  # checked by URLconf
    if post_reset_redirect is None:
        post_reset_redirect = reverse('authapp:password_reset_complete')
    else:
        post_reset_redirect = resolve_url(post_reset_redirect)
    try:
        # urlsafe_base64_decode() decodes to bytestring
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
        user = None

    if user is not None and token_generator.check_token(user, token):
        validlink = True
        title = _('Enter new password')
        if request.method == 'POST':
            form = set_password_form(user, request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(post_reset_redirect)
        else:
            form = set_password_form(user)
    else:
        validlink = False
        form = None
        title = _('Password reset unsuccessful')
    context = {
        'form': form,
        'title': title,
        'validlink': validlink,
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)


def password_reset_complete(request,
                            template_name='authapp/password_reset_complete.html',
                            extra_context=None):
    warnings.warn("The password_reset_complete() view is superseded by the "
                  "class-based PasswordResetCompleteView().",
                  RemovedInDjango21Warning, stacklevel=2)
    context = {
        'login_url': resolve_url(settings.LOGIN_URL),
        'title': _('Password reset complete'),
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)

authapp/templates/authapp/change_password.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="active">Change Password</li>
</ul>
<div class="form">
    <h3>Изменение пароля</h3>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{change_pass_form.as_table}}
        </table>
        <br>
        <a href="{% url 'main:index' %}">На главную</a>
        <input class="right" type="submit" value="Изменить">
    </form>
</div>
{% endblock %}

authapp/templates/authapp/edit.html
{%  extends 'mainapp/base.html' %}
{% load staticfiles  %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="active">Edit</li>
</ul>
<div class="form">
    <h3>Редактирование данных:</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{edit_form.as_table}}
        </table>
        <hr>
        <a href="{% url 'auth:change' %}">Изменить пароль</a>
        <input class="right" type="submit" value="Сохранить">
    </form>
</div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="active">Login</li>
</ul>
<div class="form">
    <h3>Авторизация:</h3>
    <form action="" method="post">
        {% csrf_token %}
        {% if next %}
        <input type="hidden" name="next" value="{{next}}">
        {% endif %}
        <table>
            {{ login_form.as_table }}
        </table>
        <hr>
        <a href="{% url 'auth:register' %}">Регистрация</a>
        <a href="{% url 'auth:password_reset' %}">Забыли пароль?</a>
        <input class="right" type="submit" value="Войти">
    </form>
</div>
{% endblock %}

authapp/templates/authapp/password_reset_complete.html
{% extends 'mainapp\base.html' %}

{% block title %}Password reset complete{% endblock %}

{% block content %}
<p>Your password has been set.  You may go ahead and log in now.</p>
<p><a href="{{ login_url }}">Log in</a></p>
{% endblock %}

authapp/templates/authapp/password_reset_confirm.html
{% extends 'mainapp/base.html' %}
{% block title %}Setting New password{% endblock %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="active">Change password</li>
</ul>
<div class="form">
    <h3>Forgotten your password?</h3>
    {% if validlink %}
    <form action="" method="post">
        <p>Please enter your new password twice.
            So we can verify you typed it in correctly.</p>
        <br>
        <div style="display:none">
            <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
        </div>
        <table>
            <tr>
                <th>{{ form.new_password1.errors }}
                    <label for="id_new_password1">New password:</label></th>
                <td>{{ form.new_password1 }}</td>
            </tr>
            <tr>
                <th>{{ form.new_password2.errors }}
                    <label for="id_new_password2">Confirm password:</label></th>
                <td>{{ form.new_password2 }}</td>
            </tr>
        </table>
        <br>
        <input class="right" type="submit" value="Change my password"/>
        <br>
    </form>

    {% else %}
    <form action="">
        <p>Password reset unsuccessful. <br>
            The password reset link was invalid, <br>
            possibly because it has already been used. <br>
            Please request a new password reset.</p>
    </form>
    {% endif %}
</div>
{% endblock %}

authapp/templates/authapp/password_reset_done.html
{% extends 'mainapp/base.html' %}

{% block title %}Password reset successful{% endblock %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="active">Change password</li>
</ul>
<hr>
<p>We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
<p>You should be receiving it shortly.</p>
{% endblock %}

authapp/templates/authapp/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow thelink below:
{{ protocol }}://{{ domain }}{% url 'auth:password_reset_confirm' uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

authapp/templates/authapp/password_reset_form.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="active">Change password</li>
</ul>
<div class="form">
    <h3>Forgotten your password?</h3>

    <form action="." method="post">
        <p>Enter your e-mail address to obtain a new password</p>
        <hr>
        <table>
            {{ form.as_table }}
        </table>
        <br>
        <input class="right" type="submit" value="Send e-mail">
        {% csrf_token %}
        <br>
    </form>
</div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="active">Register</li>
</ul>
<div class="form">
    <h3>Регистрация:</h3>
    <p></p>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ register_form.as_table}}
        </table>
        <hr>
        <a href="{% url 'main:index' %}">На главную</a>
        <input class="right" type="submit" value="Регистрация">
    </form>
</div>
{% endblock %}