adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

urlpatterns = [
    path('main/', adminapp.main, name='main'),
    path('persons/read/', adminapp.PersonsListView.as_view(), name='persons'),
    path('persons/create/', adminapp.PersonCreateView.as_view(), name='person_create'),
    re_path(r'^persons/update/(?P<pk>\d+)/$', adminapp.PersonUpdateView.as_view(), name='person_update'),
    re_path(r'^persons/delete/(?P<pk>\d+)/$', adminapp.PersonDeleteView.as_view(), name='person_delete'),
    path('key_words/read/', adminapp.KeywordsListView.as_view(), name='key_words'),
    path('key_words/create/', adminapp.KeywordCreateView.as_view(), name='key_word_create'),
    re_path(r'^key_words/update/(?P<pk>\d+)/$', adminapp.KeywordUpdateView.as_view(), name='key_word_update'),
    re_path(r'^key_words/delete/(?P<pk>\d+)/$', adminapp.KeywordDeleteView.as_view(), name='key_word_delete'),
    path('sites/read/', adminapp.SitesListView.as_view(), name='sites'),
    path('sites/create/', adminapp.SiteCreateView.as_view(), name='site_create'),
    re_path(r'^sites/update/(?P<pk>\d+)/$', adminapp.SiteUpdateView.as_view(), name='site_update'),
    re_path(r'^sites/delete/(?P<pk>\d+)/$', adminapp.SiteDeleteView.as_view(), name='site_delete'),
    path('pages/read/', adminapp.PagesListView.as_view(), name='pages'),
    path('pages/create/', adminapp.PageCreateView.as_view(), name='page_create'),
    re_path(r'^pages/update/(?P<pk>\d+)/$', adminapp.PageUpdateView.as_view(), name='page_update'),
    re_path(r'^pages/delete/(?P<pk>\d+)/$', adminapp.PageDeleteView.as_view(), name='page_delete'),
    path('person_page_ranks/read/', adminapp.PersonPageRanksListView.as_view(), name='person_page_ranks'),
    path('person_page_ranks/create/', adminapp.PersonPageRankCreateView.as_view(), name='person_page_rank_create'),
    re_path(r'^person_page_ranks/update/(?P<pk>\d+)/$', adminapp.PersonPageRankUpdateView.as_view(),
            name='person_page_rank_update'),
    re_path(r'^person_page_ranks/delete/(?P<pk>\d+)/$', adminapp.PersonPageRankDeleteView.as_view(),
            name='person_page_rank_delete'),
    # path('sites/link/', adminapp.sites_link, name='site_link'),
    path('sites/export/', adminapp.export, name='export'),
    path('sites/link/', adminapp.SitesLinkView.as_view(), name='site_link'),
    path('sites/link/renew/', adminapp.links_renew, name='link_renew'),
    # path('pages/detail/', adminapp.PageDetail.as_view(), name='page_detail'),
    # path('pages/detail/(<int:page>/)', adminapp.PageDetail.as_view(), name='page_detail'),
    re_path(r'^pages/detail/(?P<page>\d+)?$', adminapp.PageDetail.as_view(), name='page_detail'),
    # re_path(r'^sites/detail/view/(?P<page>\d+)$', adminapp.SiteDetailView.as_view(), name='site_detail_view'),
    # path('sites/detail/view/page<int:page>/', adminapp.PagSiteDetailView.as_view(), name='site_detail_view_pag'),
    # re_path('sites/detail/view/(?P<pk>\d+)/$', adminapp.detail_renew, name='site_detail_view'),
]

authapp/urls.py
import authapp.views as authapp
from django.urls import path, re_path
# from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm,\
#     password_reset_complete, password_change_done
# from django.conf.urls import url


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('change/', authapp.change_password, name='change'),
    path('password-reset/', authapp.password_reset, name='password_reset'),
    path('password-reset/done/', authapp.password_reset_done, name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', authapp.password_reset_confirm,
            name='password_reset_confirm'),
    path('password-reset/complete/', authapp.password_reset_complete, name='password_reset_complete'),
]

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

urlpatterns = [
    path('', mainapp.index, name='index'),
]

webadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('mainapp.urls', 'mainapp',), namespace='main')),
    path('myadmin/', include(('adminapp.urls', 'adminapp',), namespace='myadmin')),
    path('auth/', include(('authapp.urls', 'authapp',), namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

adminapp/models.py
from django.db import models


class Keywords(models.Model):
    name = models.CharField(max_length=255, unique=True)
    person = models.ForeignKey('Persons', on_delete=models.CASCADE)

    class Meta:
        db_table = "keywords"

    def __str__(self):
        return "{} ({})".format(self.name, self.person.name)


class Pages(models.Model):
    url = models.CharField(max_length=255, unique=True)
    site = models.ForeignKey('Sites', on_delete=models.CASCADE)
    found_date_time = models.DateTimeField(auto_now_add=True)
    last_scan_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = "pages"

    def __str__(self):
        return "{} ({})".format(self.url, self.site.name)


class PersonPageRank(models.Model):
    person = models.ForeignKey('Persons', on_delete=models.CASCADE)
    page = models.ForeignKey(Pages, on_delete=models.CASCADE)
    rank = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = "person_page_rank"

    def __str__(self):
        return "{} ({} {})".format(self.rank, self.person.name, self.page.url)


class Persons(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        db_table = "persons"

    def __str__(self):
        return self.name


class Sites(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        db_table = "sites"

    def __str__(self):
        return self.name

adminapp/forms.py
from django import forms
from .models import Pages


class PagesForm(forms.ModelForm):
    class Meta:
        model = Pages
        fields = ('site', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ordering_url'] = forms.ChoiceField(label='', required=False, choices=[
                ['', '----------'],
                ['url', 'min'],
                ['-url', 'max']
            ])
        self.fields['ordering_found'] = forms.ChoiceField(label='', required=False, choices=[
                ['', '----------'],
                ['found_date_time', 'min'],
                ['-found_date_time', 'max']
            ])
        self.fields['ordering_last'] = forms.ChoiceField(label='', required=False, choices=[
                ['', '----------'],
                ['last_scan_date', 'min'],
                ['-last_scan_date', 'max']
            ])
        self.fields['site'].required = False
        # self.fields.update({
        #     'ordering': forms.ChoiceField(label='sort', required='False', choices=[
        #         ['url', 'from A-Z'],
        #         ['found_date_time', 'min date create'],
        #         ['-found_date_time', 'max date create']
        #     ])
        # })

adminapp/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
# from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import user_passes_test
# from django.contrib.auth.models import User
from .models import Persons, Keywords, Sites, Pages, PersonPageRank
# from django.shortcuts import HttpResponseRedirect
from django.http import HttpResponse
import mycontext as my
from django.db.models import Count
from django.template.loader import render_to_string
from django.http import JsonResponse
from .resources import PagesResource
# from django.shortcuts import get_object_or_404
from .forms import PagesForm
from django.core import serializers
import re


def main(request):
    title = 'Главная админ'

    context = {'title': title}

    return render(request, 'adminapp/main.html', context)


class PersonsListView(ListView):
    model = Persons
    template_name = 'adminapp/objects.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.person)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PersonCreateView(CreateView):
    model = Persons
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:persons')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.person)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PersonUpdateView(UpdateView):
    model = Persons
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:persons')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.person)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PersonDeleteView(DeleteView):
    object = ''
    model = Persons
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('myadmin:persons')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.person)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class KeywordsListView(ListView):
    model = Keywords
    template_name = 'adminapp/objects.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.key_word)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class KeywordCreateView(CreateView):
    model = Keywords
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:key_words')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.key_word)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class KeywordUpdateView(UpdateView):
    model = Keywords
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:key_words')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.key_word)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class KeywordDeleteView(DeleteView):
    model = Keywords
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('myadmin:key_words')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.key_word)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class SitesListView(ListView):
    model = Sites
    template_name = 'adminapp/objects.html'
    # fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.site)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class SiteCreateView(CreateView):
    model = Sites
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:sites')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.site)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class SiteUpdateView(UpdateView):
    model = Sites
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:sites')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.site)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class SiteDeleteView(DeleteView):
    model = Sites
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('myadmin:sites')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.site)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PagesListView(ListView):
    model = Pages
    template_name = 'adminapp/objects.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.page)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PageCreateView(CreateView):
    model = Pages
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:pages')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.page)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PageUpdateView(UpdateView):
    model = Pages
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:pages')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.page)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PageDeleteView(DeleteView):
    object = ''
    model = Pages
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('myadmin:pages')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.page)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PersonPageRanksListView(ListView):
    model = PersonPageRank
    template_name = 'adminapp/objects.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.person_page_rank)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PersonPageRankCreateView(CreateView):
    model = PersonPageRank
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('myadmin:person_page_ranks')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(my.person_page_rank)
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PersonPageRankUpdateView(UpdateView):
    model = PersonPageRank
    template_name = 'adminapp/object_update.html'

adminapp/templates/adminapp/main.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'main:index' %}">Главная</a></li>
    <li class="active">Admin</li>
</ul>
<div class="front_menu left">
    <a href="">Общая статистика</a>
    <a href="">Ежедневная статистика</a>
    <p>Справочники</p>
    <ul>
        <li><a href="{% url 'myadmin:persons' %}">Личности</a></li>
        <li><a href="{% url 'myadmin:key_words' %}">Ключевые слова</a></li>
        <li><a href="{% url 'myadmin:sites' %}">Сайты</a></li>
        <li><a href="{% url 'myadmin:pages' %}">Страницы</a></li>
        <li><a href="{% url 'myadmin:person_page_ranks' %}">Рейтинг</a></li>
        <li><a href="{% url 'myadmin:site_link' %}">Подробно сайты</a></li>
        <li><a href="{% url 'myadmin:page_detail' %}">Подробно страницы</a></li>
    </ul>
</div>
{% block main %}
{% endblock %}
{% endblock %}

adminapp/templates/adminapp/object_delete.html
{% extends 'adminapp/main.html' %}
{% load staticfiles %}
{% block main %}
<div class="items">
    <div>
        Уверены, что хотите удалить <strong>{{object.name}}</strong>?
    </div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <hr>
        <input type="submit" value="удалить">
        <input type="button" onclick="location.href='{% url link %}'" value="к списку">
    </form>
</div>
{% endblock %}

adminapp/templates/adminapp/object_update.html
{% extends 'adminapp/main.html' %}
{% load staticfiles %}
{% block main %}
<div class="form">
    <form action="" method="post" enctype="multipart/form-data">
        <table>
            {% csrf_token %}
            {{form.as_table}}
        </table>
        <hr>
        <input type="submit" value="сохранить">
        <input type="button" onclick="location.href='{% url link %}'" value="к списку">
    </form>
</div>
{% endblock %}

adminapp/templates/adminapp/objects.html
{% extends 'adminapp/main.html' %}
{% load staticfiles %}
{% block main %}
<div class="objects_list left">
    <div class="box">
        <h3>Справочник {{hdbk}}</h3>
        <br>
        <table class="table">
            <tr>
                <th>{{caption}}</th>
            </tr>
            {% for object in object_list %}
            <tr>
                <td>
                    {% comment %} <!--{% if name == 'person_page_rank' %}-->
                    <!--{{object.rank}}-->
                    <!--{% endif %}-->
                    <!--{% if name == 'page' %}-->
                    <!--{{object.url}}-->
                    <!--{% else %}-->
                    <!--{{object.name}}-->{% endcomment %}
                    {% if name == 'person_page_rank' %}
                    {{object.rank}}
                    {% endif %}
                    {% if name == 'page' %}
                    {{object.url}}
                    {% else %}
                    {{object.name}}
                    {% endif %}
                    <a href="{% url link_delete object.pk %}">delete</a>
                    <a href="{% url link_update object.pk %}">edit</a>
                </td>
            </tr>
            {% endfor%}
        </table>
        <hr>
        <button onclick="location.href='{% url link_create %}'">Добавить</button>
        {% if request.path == '/myadmin/pages/read/' %}
        <button onclick="location.href='{% url 'adminapp:export' %}'">Экспорт</button>
        {% endif %}
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/site_detail.html
{% extends 'adminapp/main.html' %}
{% load staticfiles %}
{% block main %}
<div class="objects_list left ajax">
    <div class="box site_link">
        <h3>Детальная инормация по сайтам</h3>
        <br>
        <table class="table site_link ajax_renew">
             {% include 'adminapp/includes/inc_detail.html' %}
        </table>
        <hr>
        <input type="button" value="Обновить">
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/site_detail_view.html
{% extends 'adminapp/main.html' %}
{% load staticfiles %}
{% load my_tags %}
{% block main %}
<div class="objects_list left">
    <div class="box site_link">
        <h3>Детальная инормация по страницам сайтов сайтов</h3>
        <br>
        <form action="" method="get">
            <table class="table site_link">
                <tr>
                    <th>Сайт</th>
                    <th>Страница</th>
                    <th>Дата создания</th>
                    <th>Дата посещения</th>
                </tr>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.site.name }}</td>
                    <td>{{ object.url }}</td>
                    <td>{{ object.found_date_time }}</td>
                    <td>{{ object.last_scan_date}}</td>
                </tr>
                {% endfor %}
                <tr>
                    {% for object in site %}
                    <th>
                        {{ object }}
                    </th>
                    {% endfor%}
                </tr>
            </table>
            <hr>
            <div class="paginate">
                {% if paginator.num_pages > 1 %}
                {% if page_obj.has_previous %}
                <a class="left_pag" href="?{% query_update request.GET 'page' page_obj.previous_page_number %}"><<</a>
                {% endif %}
                <span class="center_pag">{{ paginator.num_pages }}</span>
                {% if page_obj.has_next %}
                <a class="right_pag" href="?{% query_update request.GET 'page' page_obj.next_page_number %}">>></a>
                {% endif %}
                {% endif %}
            </div>
            <input type="submit" value="Применить">
        </form>
    </div>
</div>
{% endblock %}
